### ISSUE TITLE
Issues connecting Digilent hs3 to Vivado 2022.1 

### ISSUE THREAD

**Issue by ktwillia9** [roguepengu1n/zturn_breakout#1]
Have you actually had any success connecting to the z-turn board with the hs3?
I cannot get Vivado and the Digilent hs3 to recognize the z-turn board with any clock speed.

**Comment by roguepengu1n** [comment]
If you are talking about using the hardware in this repo to connect the HS3 to the Z-Turn board, only the V0.1 was tested and indeed works. V1.0 should work the same. 

Please ensure your soldering is good on the adapter and that the configuration jumpers on the z-turn board are set for JTAG.
